# Generated by Django 2.1.2 on 2018-10-30 11:08

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-posta')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='İsim')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon Numarası')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff Status')),
                ('status', models.CharField(choices=[('E-Mail doğrulaması gerekli.', 'E-Mail Doğrulaması gerekli.'), ('Üyelik işlemi tamamlandı.', 'Üyelik işlemi tamamlandı.')], default='E-Mail doğrulaması gerekli.', max_length=50, null=True, verbose_name='Üyelik Aşaması')),
                ('is_manager', models.BooleanField(default=False, verbose_name='Manager')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('email_confirmation_token', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('email_confirmation_expire_date', models.DateTimeField(blank=True, null=True)),
                ('password_confirmation_token', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('password_confirmation_expire_date', models.DateTimeField(blank=True, null=True)),
                ('is_email_send', models.BooleanField(default=False, verbose_name='Onay E-postası Gönderildi mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Kullanıcı',
                'verbose_name_plural': 'Kullanıcılar',
                'ordering': ('-created_at',),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
