# Generated by Django 2.1.2 on 2018-10-30 11:18

from django.db import migrations
import filmAdvice.profile.managers


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('objects', filmAdvice.profile.managers.FilmUserManager()),
            ],
        ),
    ]
