# Generated by Django 2.1.2 on 2018-10-30 11:08
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=150, verbose_name='Film Adı')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kayıt Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Filmler',
                'ordering': ('-created_at',),
            },
        ),
    ]
