# Generated by Django 2.1.2 on 2018-11-26 20:03

from django.db import migrations, models
from django.utils.text import slugify
from filmAdvice.settings import APP_MAIN_CURRENT_PATH
from filmAdvice.system.constant import *
import csv


def inital_movie_data(apps):
    with open(APP_MAIN_CURRENT_PATH + SYSTEM_APP_PATH + DATASET_MOVIES_FILE, encoding='utf-8') as f:
        reader = csv.DictReader([line.replace('::', '\t') for line in f],
                                fieldnames='MovieID::Title::Genres'.split('::'), delimiter='\t')

    Movie = apps.get_model('movie', 'Movie')
    for row in reader:
        movie = Movie.get_object_or_create(movie_id=row['MovieID'], movie_name=row['Title'])
        movie.save()
    return reader


def slugify_title(apps, schema_editor):
    Movie = apps.get_model('movie', 'Movie')
    for movie in Movie.objects.all():
        movie.slug = slugify(movie.movie_name)
        movie.save()


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb_id',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=10, verbose_name='IMDB ID'),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_id',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=10, verbose_name='Film ID'),
        ),
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_name',
            field=models.CharField(default='', max_length=150, verbose_name='Film Adı'),
        ),
        migrations.RunPython(inital_movie_data),
        migrations.RunPython(slugify_title),
    ]
