# Generated by Django 2.1.2 on 2018-11-26 21:39

from django.db import migrations
from django.utils.text import slugify
from filmAdvice.settings import APP_MAIN_CURRENT_PATH
from filmAdvice.system.constant import *
import csv


class Migration(migrations.Migration):

    initial = True

    def inital_movie_data(apps, schema_editor):
        with open(APP_MAIN_CURRENT_PATH + SYSTEM_APP_PATH + DATASET_MOVIES_FILE, 'r', encoding='utf-8') as f:
            reader = csv.DictReader([line.replace(',', '\t') for line in f],
                                    fieldnames='movieId,title,genres'.split(','), delimiter='\t')

        Movie = apps.get_model('movie', 'Movie')
        for row in reader:
            try:
                for movie in Movie.objects.all():
                    movie.movie_id = int(row['movieId'])
                    movie.movie_name = row['title']
                    print(movie)
                    movie.save()
            except:
                pass
        return reader

    def slugify_title(apps, schema_editor):
        Movie = apps.get_model('movie', 'Movie')
        for movie in Movie.objects.all():
            movie.slug = slugify(movie.movie_name)
            movie.save()

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(inital_movie_data),
    ]
