# Generated by Django 2.1.2 on 2018-11-26 21:37

from django.db import migrations
from django.utils.text import slugify
from filmAdvice.settings import APP_MAIN_CURRENT_PATH
from filmAdvice.system.constant import *
import csv
from django.apps import apps


class Migration(migrations.Migration):

    def inital_movie_data(**kwargs):
        with open(APP_MAIN_CURRENT_PATH + SYSTEM_APP_PATH + DATASET_MOVIES_FILE, encoding='utf-8') as f:
            reader = csv.DictReader([line.replace('::', '\t') for line in f],
                                    fieldnames='MovieID::Title::Genres'.split('::'), delimiter='\t')

        Movie = apps.get_model('movie', 'Movie')
        for row in reader:
            print(reader)
            Movie.objects.create(movie_id=row['MovieID'], movie_name=row['Title'])
            # movie.save()
        return reader

    def slugify_title(apps, schema_editor):
        Movie = apps.get_model('movie', 'Movie')
        for movie in Movie.objects.all():
            movie.slug = slugify(movie.movie_name)
            movie.save()

    dependencies = [
        ('movie', '0002_auto_20181126_2303'),
    ]

    operations = [
    ]





