# Generated by Django 2.1.2 on 2019-01-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_recommend'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_pic',
            field=models.ImageField(blank=True, null=True, upload_to='pic_folder/', verbose_name='Afiş'),
        ),
    ]
