# Generated by Django 2.1.2 on 2018-11-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20181127_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb_id',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='IMDB ID'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_id',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Film ID'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Film Adı'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Film Slug'),
        ),
    ]
