# Generated by Django 2.1.2 on 2019-01-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_movie_movie_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_pic_url',
            field=models.URLField(blank=True, null=True, verbose_name='Afis URL'),
        ),
    ]
