# Generated by Django 2.1.5 on 2019-01-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_movie_movie_pic_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_pic_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Afis URL'),
        ),
    ]
