# Generated by Django 2.1.5 on 2019-02-14 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_auto_20190130_1902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommend',
            options={'ordering': ('-created_at',), 'verbose_name': 'Tahminler', 'verbose_name_plural': 'Tahminler'},
        ),
        migrations.AlterModelOptions(
            name='watchhistory',
            options={'ordering': ('-created_at',), 'verbose_name': 'İzleme Geçmişim', 'verbose_name_plural': 'İzleme Geçmişim'},
        ),
        migrations.AlterModelOptions(
            name='watchlist',
            options={'ordering': ('-created_at',), 'verbose_name': 'İzleme Listem', 'verbose_name_plural': 'İzleme Listem'},
        ),
    ]
